# Tendencias e Innovacion en Tecnologia Agricola (TEA)
tipodeDatos = input("Que tipos de datos sale en la consola 1.2.1 ? ")
print(tipodeDatos)
tipodeDatos = input("Que tipos de datos sale en la consola 1.2.2 ? ")
print(tipodeDatos)
tipodeDatos = input("Que tipos de datos sale en la consola 1.2.3 ? ")
print(tipodeDatos)
nombrecompleto = input("Cual es tu nombre comppleto ? ")
print(nombrecompleto)
correo = input("Cuál es su correo ? ")
print(correo)
direccion = input("Cuál es la direccion de su repositorio de codigo fuente ? ")
print(direccion)
